management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  application:
    name: 'testbot'

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    threads: ${TELEGRAM_BOT_THREADS}